### ISSUE TITLE
Order of Events in the narrative

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#31] opened 2021-08-21 23:39 UTC
One of the key features we're looking for to explore in narrative theory would be changing the order of events and modifying the way narrative is told accordingly, which is not currently embedded in the system.

**Comment by nickmontfort** [comment] 2021-08-23 03:15
Absolutely. We need to add several solid test cases (for retrograde, random, and hard-coded orders, to begin with) in test/spin.
These can all be in order.html, order.js.
Then we can work on fixing this and check to see if the fixes work.

**Comment by arthalun** [comment] 2021-08-23 05:28
Yes, indeed. I will write and push a test case very soon.

**Comment by nickmontfort** [comment] 2021-08-23 13:08
You can add things to `tmp` (as you did) for purposes of work and discussion, but here I'm looking for several specific pairs of files to be added to `test/spin` because we need to keep them as regression tests. In that directory, add `retrograde.js' and 'retrograde.html' along with other pairs that narrate the spin test story in different ways, checking the basic cases of order being changed.

**Comment by anjchang** [comment] 2021-08-23 14:49
Should we be adding a key into the narrator file?
<pre>
var spin = {
   order: random;
};
</pre>
Does  the value, e.g."random" have to be in quotes?

**Comment by anjchang** [comment] 2021-08-23 15:29
Whoops, it turns out I had to update my index.html to point to the right narrator file.

**Comment by nickmontfort** [comment] 2021-08-24 03:25
I have added the test cases in `test/spin` as `random` and `retrograde`. Re-ordering is working now but the appropriate tense changes are not yet being applied. That will be work tomorrow.

**Comment by nickmontfort** [comment] 2021-08-24 21:38
Having opened 39, the issue with tense here is now included in that broader issue. The actual re-ordering of events (at least random and retrograde) works, as does timePhrases, so I am closing this, with the more general issue 39 still open.

**Closed by nickmontfort** 2021-08-24 21:38 UTC
Labels: bug
